os: Visual Studio 2015

environment:
  HOME: "%HOMEDRIVE%%HOMEPATH%"
  PYTHON: C:\Python27
  SCONS_CACHE_ROOT: "%HOME%\\scons_cache"
  SCONS_CACHE_LIMIT: 1024
  GODOT_REPO_URL: "https://github.com/godotengine/godot"
  matrix:
    - VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      GD_PLATFORM: windows
      TOOLS: yes
      TARGET: release_debug
      ARCH: amd64

cache:
  - "%SCONS_CACHE_ROOT%"

install:
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install -U wheel  # needed for pip install scons to work, otherwise a flag is missing
  - pip install scons==3.0.1
  - if defined VS call "%VS%" %ARCH%  # if defined - so we can also use mingw

before_build:
  # Get Godot source and install the module
  - cd %APPVEYOR_BUILD_FOLDER%\..
  - git clone --depth=1 %GODOT_REPO_URL% -b 3.2 --single-branch && cd godot
  - mklink /d modules\anl %APPVEYOR_BUILD_FOLDER%

  - echo %GD_PLATFORM%
  - python --version
  - scons --version
  - cl.exe
  - SET "SCONS_CACHE=%SCONS_CACHE_ROOT%\master"

build_script:
- scons platform=%GD_PLATFORM% target=%TARGET% tools=%TOOLS% debug_symbols=no verbose=yes progress=no gdnative_wrapper=yes